baseURL = 'https://slongpre.com/'
languageCode = 'en-us'
title = 'Simon Longpré-Landry'
theme = "dimension"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true